spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/dataflow
spring.datasource.username=poysmon
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

file.storage.location=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
data-service.base-url=${DATA_SERVICE_BASE_URL:http://127.0.0.1:8000}
spring.jackson.property-naming-strategy=SNAKE_CASE